CREATE SCHEMA IF NOT EXISTS filmaviu;

CREATE TABLE filmaviu.TEMPORADAS(
    "NUMERO" INT NOT NULL,
    "SERIE_ID" MEDIUMINT NOT NULL,
    "ID" VARCHAR(36) UNIQUE NOT NULL,
    "FECHA_LANZAMIENTO" DATE NOT NULL,
    CONSTRAINT PK_TEMPORADA PRIMARY KEY("NUMERO", "SERIE_ID"),
);

CREATE TABLE filmaviu.EPISODIOS(
    "ID" VARCHAR(36) NOT NULL,
    "TEMPORADA_ID" VARCHAR(36) NOT NULL,
    "NUMERO" INT NOT NULL,
    "TITULO" VARCHAR(255) NOT NULL,
    CONSTRAINT PK_EPISODIO PRIMARY KEY("ID")
);

CREATE TABLE filmaviu.SERIE_IDIOMAS(
    "ID_SERIE" MEDIUMINT NOT NULL,
    "ID_IDIOMA" MEDIUMINT NOT NULL,
    "TIPO" ENUM('AUDIO', 'SUBTITULO') NOT NULL,
    CONSTRAINT PK_SERIE_IDIOMA PRIMARY KEY("ID_SERIE", "ID_IDIOMA", "TIPO")
);

CREATE TABLE filmaviu.SERIES(
    "ID" MEDIUMINT NOT NULL AUTO_INCREMENT,
    "TITULO" VARCHAR(255) NOT NULL,
    "PLATAFORMA" MEDIUMINT NOT NULL,
    "DIRECTOR" MEDIUMINT NOT NULL,
    "CLASIFICACION" VARCHAR(36) NOT NULL,
    "GENERO" VARCHAR(36) NOT NULL,
    CONSTRAINT PK_SERIE PRIMARY KEY("ID")
);

CREATE TABLE filmaviu.SERIE_ACTORES(
    "ID_SERIE" MEDIUMINT NOT NULL,
    "ID_ACTOR" MEDIUMINT NOT NULL,
    CONSTRAINT PK_SERIE_ACTORES PRIMARY KEY("ID_SERIE", "ID_ACTOR")
);

CREATE TABLE filmaviu.GENEROS(
    "ID" VARCHAR(36) NOT NULL,
    "NOMBRE" VARCHAR(255) NOT NULL,
    CONSTRAINT PK_GENERO PRIMARY KEY("ID")
);

CREATE TABLE filmaviu.PLATAFORMAS(
    "ID" MEDIUMINT NOT NULL AUTO_INCREMENT,
    "NOMBRE" VARCHAR(255) NOT NULL,
    CONSTRAINT PK_PLATAFORMA PRIMARY KEY("ID")
);

CREATE TABLE filmaviu.DIRECTORES(
    "ID" MEDIUMINT NOT NULL AUTO_INCREMENT,
    "NOMBRE" VARCHAR(255) NOT NULL,
    "APELLIDOS" VARCHAR(500) NOT NULL,
    "FECHA_NACIMIENTO" DATE NOT NULL,
    "NACIONALIDAD" VARCHAR(36) NOT NULL,
    CONSTRAINT PK_DIRECTOR PRIMARY KEY("ID")
);

CREATE TABLE filmaviu.ACTORES(
    "ID" MEDIUMINT NOT NULL AUTO_INCREMENT,
    "NOMBRE" VARCHAR(255) NOT NULL,
    "APELLIDOS" VARCHAR(500) NOT NULL,
    "FECHA_NACIMIENTO" DATE NOT NULL,
    "NACIONALIDAD" VARCHAR(36) NOT NULL,
    CONSTRAINT PK_ACTOR PRIMARY KEY("ID")
);

CREATE TABLE filmaviu.CLASIFICACIONES(
    "ID" VARCHAR(36) NOT NULL,
    "TIPO" VARCHAR(255) NOT NULL,
    CONSTRAINT PK_CLASIFICACION PRIMARY KEY("ID")
);

CREATE TABLE filmaviu.IDIOMAS(
    "ID" MEDIUMINT NOT NULL AUTO_INCREMENT,
    "NOMBRE" VARCHAR(255) NOT NULL,
    "ISO_CODE" VARCHAR(255) UNIQUE NOT NULL,
    CONSTRAINT PK_IDIOMA PRIMARY KEY("ID")
);

CREATE TABLE filmaviu.PELICULAS(
    "ID" MEDIUMINT NOT NULL AUTO_INCREMENT,
    "TITULO" VARCHAR(255) NOT NULL,
    "PLATAFORMA" MEDIUMINT NOT NULL,
    "DIRECTOR" MEDIUMINT NOT NULL,
    "PUNTUACION" FLOAT NOT NULL,
    "CLASIFICACION" VARCHAR(36) NOT NULL,
    "GENERO" VARCHAR(36) NOT NULL,
    CONSTRAINT PK_PELICULA PRIMARY KEY("ID")
);

CREATE TABLE filmaviu.PELICULA_ACTORES(
    "ID_PELICULA" MEDIUMINT NOT NULL,
    "ID_ACTOR" MEDIUMINT NOT NULL,
    CONSTRAINT PK_PELICULA_ACTOR PRIMARY KEY("ID_PELICULA", "ID_ACTOR")
);

CREATE TABLE filmaviu.NACIONALIDADES(
    "ID" VARCHAR(36) NOT NULL,
    "PAIS" VARCHAR(255) NOT NULL,
    CONSTRAINT PK_NACIONALIDAD PRIMARY KEY("ID")
);

CREATE TABLE filmaviu.PELICULA_IDIOMAS(
    "ID_PELICULA" MEDIUMINT NOT NULL,
    "ID_IDIOMA" MEDIUMINT NOT NULL,
    "TIPO" ENUM('AUDIO', 'SUBTITULO') NOT NULL,
    CONSTRAINT PK_PELICULA_IDIOMA PRIMARY KEY("ID_PELICULA", "ID_IDIOMA", "TIPO")
);